# Generated by Django 4.2.8 on 2024-01-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_role', '0001_initial'),
        ('personal_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date_credit', models.DateTimeField(verbose_name='Fecha desde')),
                ('date_initial', models.DateTimeField(verbose_name='Fecha hasta')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Interes(%)')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Interes')),
                ('value_interest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Prestamo')),
                ('nume_quota', models.IntegerField(blank=True, null=True, verbose_name='Numero Cuotas')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
                ('status', models.BooleanField(default=False, verbose_name='Procesado')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observacion')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('calendar_processed', models.IntegerField(blank=True, null=True, verbose_name='Calendario Procesado')),
                ('status_processed', models.BooleanField(default=False, verbose_name='Activo Procesado')),
                ('balance_processed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Procesado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_file.employee', verbose_name='Empleado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_role.item', verbose_name='Tipo Descuento')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreditsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date_discount', models.DateTimeField(verbose_name='Fecha Descuento')),
                ('quota', models.IntegerField(default=0, verbose_name='Numero Cuota')),
                ('status', models.BooleanField(choices=[(1, 'pendiente'), (2, 'Rol'), (3, 'Comprobante')], default=1, verbose_name='Procesado')),
                ('balance_quota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Cuota')),
                ('calendar_quota_processed', models.IntegerField(blank=True, null=True, verbose_name='Calendario Procesado')),
                ('status_quota_processed', models.BooleanField(default=False, verbose_name='Activo Procesado')),
                ('balance_quota_processed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Procesado cuots')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_debt.credit', verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Prestamo Detalle',
                'verbose_name_plural': 'Prestamos Detalles',
                'ordering': ['id'],
            },
        ),
    ]
