# Generated by Django 4.2.8 on 2024-01-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
