# Generated by Django 4.2.8 on 2024-01-19 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personal_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pagina web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('state', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('state', models.BooleanField(default=True, verbose_name='Activo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_training.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('-id',),
                'permissions': (('training_modify_supplier', 'Colocar proveedor Course'), ('training_modify_dates', 'Colocar fechas Course')),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('note', models.IntegerField(blank=True, verbose_name='Nota')),
                ('certificado_pdf', models.FileField(upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_training.course', verbose_name='Curso')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_file.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('year', models.IntegerField(verbose_name='Año Curso')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('approved_boss', models.BooleanField(default=False, verbose_name='Aprobado jefe')),
                ('approved_commission', models.BooleanField(default=False, verbose_name='Aprobado Comision')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Costo Curso')),
                ('state', models.BooleanField(default=False, verbose_name='Activo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_training.course', verbose_name='Curso')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_file.employee', verbose_name='Empleado')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ('-id',),
                'permissions': (('application_approve_boss', 'Aprobar solicitud por jefe Application'), ('application_approve_commission', 'Aprobar solicitud por comision Application'), ('application_add_cost', 'Colocar costo de la solicitud Application')),
            },
        ),
    ]
