# Generated by Django 4.2.8 on 2024-01-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('-id',), 'permissions': (('certificate_view_pdf', 'Ver certificado Certificate'),), 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
