# Generated by Django 4.2.8 on 2024-01-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_file', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Apellidos')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='empleado', verbose_name='Foto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direction', models.CharField(max_length=100, null=True, verbose_name='Dirección')),
                ('phone', models.IntegerField(null=True, verbose_name='Telefono')),
                ('curriculum', models.FileField(blank=True, help_text='Sube tu Curriculum en formato PDF.', null=True, upload_to='curriculum/', verbose_name='Curriculum')),
                ('presentation_letter', models.FileField(blank=True, help_text='Sube tu carta de presentación en formato PDF.', null=True, upload_to='cartas_presentacion/', verbose_name='Carta de Presentación')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('name_offer', models.CharField(max_length=1000, null=True, verbose_name='Nombre Oferta')),
                ('offer_description', models.CharField(max_length=1000, null=True, verbose_name='Descripcion Oferta')),
                ('requirements', models.FileField(blank=True, null=True, upload_to='requirements/', verbose_name='Requisitos')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salario')),
                ('publication_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de publicacion')),
                ('deadline', models.DateField(verbose_name='Fecha de Cierre')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Activo')),
                ('vacancy_numbers', models.IntegerField(verbose_name='Vacantes disponibles')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_file.area', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('fecha_resultado', models.DateField()),
                ('resultado', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], max_length=100)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ganador', models.BooleanField(default=False)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_selection.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PruebaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('requerimiento', models.FileField(blank=True, help_text='Sube tu prueba_tecnica en formato PDF.', null=True, upload_to='prueba_tecnica/', verbose_name='prueba_tecnica')),
                ('fecha_limite', models.DateField()),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_selection.offer', verbose_name='Oferta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('inicial', 'Entrevista Inicial'), ('final', 'Entrevista Final')], max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('entrevistador', models.CharField(max_length=200)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_selection.candidate')),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_selection.offer', verbose_name='Oferta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('numero_contrato', models.CharField(max_length=100, unique=True, verbose_name='Número de Contrato')),
                ('contract_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha del Contrato')),
                ('start_date_of_work', models.DateField(null=True, verbose_name='Inicio del Contrato')),
                ('finish_date_of_work', models.DateField(null=True, verbose_name='Final del Contrato')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_selection.candidate', verbose_name='Candidato')),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_selection.offer', verbose_name='Oferta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('type_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_file.typecontract', verbose_name='Tipo Contrato')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'contracts',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('titulo_clausula', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_selection.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='name_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_selection.offer', verbose_name='Cargo a postular'),
        ),
        migrations.CreateModel(
            name='AsignacionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_entrega', models.TextField()),
                ('archivo_prueba', models.FileField(blank=True, help_text='Sube tu entrega_prueba en formato PDF,rar.', null=True, upload_to='entrega_prueba/', verbose_name='entrega_prueba')),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'incompleta'), (3, 'Satisfactoria')])),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_selection.candidate')),
                ('prueba_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_selection.pruebatecnica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
